---
galaxy_info:
  author: "Ansible Role Author"
  description: "Deploy Mimir time-series database in single-binary mode with S3/Garage backend"
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "all"
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - monitoring
    - mimir
    - timeseries
    - s3
    - vault

dependencies: []
