---
galaxy_info:
  author: Scott Schlaefli
  description: Install and configure Grafana on Alpine Linux
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Alpine
      versions:
        - all

dependencies: []
