---
galaxy_info:
  author: Scott Schlaefli
  description: Install and configure Grafana on Debian/Ubuntu
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
