---
all:
  children:
    homelab:
      children:
        proxmox:
          hosts:
            pve01:
              ansible_host: 10.20.0.11
            pve02:
              ansible_host: 10.20.0.12
            pve03:
              ansible_host: 10.20.0.13
        nas:
          hosts:
            nas1:
              ansible_host: 10.20.0.5
        monitoring:
          hosts:
            lxc-loki:
              ansible_host: 10.20.1.8
            lxc-mimir:
              ansible_host: 10.20.1.7
            lcx-prometheus-pve-exporter:
              ansible_host: 10.20.0.101
            lxc-grafana:
              ansible_host: 10.20.1.6
        dns:
          hosts:
            lxc-dns-1:
              ansible_host: 10.20.0.50
            lxc-dns-2:
              ansible_host: 10.20.0.51
        security:
          hosts:
            lxc-hashicorpvault:
              ansible_host: 10.20.1.9
        media:
          hosts:
            lxc-plex:
              ansible_host: 10.20.1.101
        kubernetes:
          children:
            rke2rancher:
              hosts:
                rke2-m1:
                  ansible_host: 10.20.1.11
                rke2-m2:
                  ansible_host: 10.20.1.12
                rke2-m3:
                  ansible_host: 10.20.1.13
            rke2workload:
              children:
                rke2workloadcontrol:
                  hosts:
                    rke2-w-c1:
                      ansible_host: 10.20.1.21
                    rke2-w-c2:
                      ansible_host: 10.20.1.22
                    rke2-w-c3:
                      ansible_host: 10.20.1.23
                rke2workloadworker:
                  hosts:
                    rke2-w-w1:
                      ansible_host: 10.20.1.31
                    rke2-w-w2:
                      ansible_host: 10.20.1.32
                    rke2-w-w3:
                      ansible_host: 10.20.1.33
