---
galaxy_info:
  author: "Scott Schlaefli"
  description: "Deploy Grafana Alloy for metrics and log collection"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Alpine
      versions:
        - "3.16"
        - "3.17"
        - "3.18"
        - "3.19"
        - "3.20"
        - "3.21"
        - "3.22"
        - "3.23"
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - monitoring
    - metrics
    - logs
    - grafana
    - alloy
    - prometheus
    - loki

dependencies: []
