---
- name: Restart grafana
  ansible.builtin.service:
    name: grafana
    state: restarted
    enabled: true

- name: Reload grafana
  ansible.builtin.service:
    name: grafana
    state: reloaded
