---
# Handlers for Grafana Alloy role

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart alloy
  service:
    name: alloy
    state: restarted
    enabled: true

- name: reload alloy
  service:
    name: alloy
    state: reloaded
