---
# Handlers for Grafana Alloy role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart alloy
  ansible.builtin.service:
    name: alloy
    state: restarted
    enabled: true

- name: Reload alloy
  ansible.builtin.service:
    name: alloy
    state: reloaded
